---
language: java
jdk: openjdk9

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

branches:
  only:
    - master
    - /^travis.*/

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      install: skip
      after_success: bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: script
          script: mvn deploy --settings .maven.xml -DskipTests=true -DdoDokka=true -B

    - stage: deploy
      script: skip
      install: skip
      before_script:
        - DEPLOY_DOCS=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null | grep -v SNAPSHOT) || echo "Snapshot detected, skipping doc deploy"
      deploy:
        - provider: script
          script: mvn site --settings .maven.xml -DskipTests=true -DdoDokka=true -B && git add dokka
          on:
            tags: false
            condition: $DEPLOY_DOCS
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          verbose: true
          local_dir: ./dokka
          on:
            tags: false
            condition: $DEPLOY_DOCS
